version: '2'
services:
  master:
    build: .
    command: bin/spark-class org.apache.spark.deploy.master.Master -h master
    hostname: master
    environment:
      MASTER: spark://master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: localhost
    expose:
      - 10000
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    extra_hosts:
      - "parent-host:$DOCKERHOSTIP"
    ports:
      - 10000:10000
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    volumes:
      - ./conf/master:/conf
      - ./tmpdata:/tmp/data
    volumes_from:
      - datadir

  datadir:
    image: busybox:latest
    volumes:
      - ./data:/opt/data:ro
      - ./checkpoints:/opt/checkpoints

  worker:
    build: .
    command: bin/spark-class org.apache.spark.deploy.worker.Worker -c 2 spark://master:7077
    hostname: worker
    depends_on:
      - master
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
    links:
      - master
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
    extra_hosts:
      - "parent-host:$DOCKERHOSTIP"
    ports:
      - 8081:8081
    volumes:
      - ./conf/worker:/conf
      - ./tmpdata:/tmp/data
    volumes_from:
      - datadir
